# -*- coding: utf-8 -*-
"""mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LCyOKM9IqM2MPJklGRiiDn1aQfKYnCfK
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
print("Original shapes:", x_train.shape, x_test.shape)

x_train = x_train.astype('float32') / 255.0
x_test  = x_test.astype('float32') / 255.0

x_train = x_train.reshape(-1, 28, 28, 1)
x_test  = x_test.reshape(-1, 28, 28, 1)

y_train = y_train.reshape(-1)
y_test  = y_test.reshape(-1)

print("After preprocessing:", x_train.shape, x_test.shape)
print("Label shapes:", y_train.shape, y_test.shape)

datagen = ImageDataGenerator(
    rotation_range=5,
    width_shift_range=0.05,
    height_shift_range=0.05,
    zoom_range=0.1
)

datagen.fit(x_train)
print("Data augmentation ready!")

model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.BatchNormalization(),
    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Dropout(0.25),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.BatchNormalization(),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Dropout(0.25),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),
    layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

early_stop = EarlyStopping(monitor='val_accuracy', patience=3, restore_best_weights=True)

history = model.fit(
    datagen.flow(x_train, y_train, batch_size=128, shuffle=True),
    epochs=15,
    validation_data=(x_test, y_test),
    callbacks=[early_stop]
)

test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print(f"\nTest accuracy: {test_acc*100:.2f}%")

plt.figure(figsize=(10,4))
plt.subplot(1,2,1)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.legend(); plt.title("Loss per Epoch")

plt.subplot(1,2,2)
plt.plot(history.history['accuracy'], label='Train Acc')
plt.plot(history.history['val_accuracy'], label='Val Acc')
plt.legend(); plt.title("Accuracy per Epoch")
plt.show()

model.save("digit_classifier.keras")
print("Model saved as 'digit_classifier.keras'")

from google.colab import files
files.download("digit_classifier.keras")

x_sample = x_train[0].reshape((1, 28, 28, 1))
plt.figure(figsize=(8,8))
for i, batch in enumerate(datagen.flow(x_sample, batch_size=1)):
    plt.subplot(3,3,i+1)
    plt.imshow(batch[0].reshape(28,28), cmap='gray')
    plt.axis('off')
    if i == 8:
        break
plt.suptitle("Examples of Augmented Digits")
plt.show()